<?php
/**
 * Magento

 *
 * @category    design
 * @package     brainworx_custom
 * @copyright   Copyright (c) Brainworx bvba
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="fieldset">
    
    <?php if( $this->isSeller() ): ?>

    <div class="page-title">
		<h1><?php echo $this->__('Seller Information') ?></h1>
	</div>
     
        <ul class='form-list'>
            <li class="fields">
                <p>
                    <label> <?php echo $this->__('Name: ') ?></label>
                    <?php echo $this->escapeHtml($this->getSellerName()) ?>
            </p></li>
            <li class="fields">
                <p>
                    <label> <?php echo $this->__('Unique Link: ') ?></label>
                    <a href='<?php echo $this->escapeHtml($this->getSellerUniqueLink()) ?>'><?php echo $this->escapeHtml($this->getSellerUniqueLink()) ?></a>
                    <?php echo $this->getExtraSellerInfo()?>
            </p></li>
    
        </ul>
    
    <?php endif; ?>
</div>
