<!-- Brainworx: added link to request change order 
13/5 removed status  $_order->getStatusLabel() ?></em></td>-->
<div class="page-title">
<h1><?php echo $this->__('Overzicht bestellingen via jou') ?></h1>
</div>
<?php 
	  $_orders = $this->getOrders();
	  
	  $currentpage = Mage::getBlockSingleton('page/html_pager')->getCurrentPage();
	  $perpage = Mage::getBlockSingleton('page/html_pager')->getLimit();
	  $_orders->getSelect()->limitPage($currentpage, $perpage);
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php echo $this->getChildHtml('info');?>
<?php echo $this->getPagerHtml();?>
<?php if($_orders->getSize()): ?>
<table class="data-table orders" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th class="number"><?php echo $this->__('Bestelling #') ?></th>
            <th class="date"><?php echo $this->__('Datum') ?></th>
            <th class="ship"><?php echo $this->__('Verzendadres') ?></th>
            <th class="total"><span class="nobr"><?php echo $this->__('Totaal') ?></span></th>
            <th class="view">&nbsp;</th>
            <th class="view">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; $contact=Mage::getBaseUrl().'/contacts';$bur= Mage::helper('core/url')->getCurrentUrl();?>
        <?php foreach ($_orders as $_order): ?>
        <tr>
            <td class="number"><?php echo $_order->getRealOrderId() ?></td>
            <td class="date"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
            <td class="ship"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
            <td class="total"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
            <td class="a-center view">
                 <span class="nobr"><a href="<?php echo $contact.'?bur='.$bur.'&cmt='.urlencode($this->__('Betreft Bestelling ').$_order->getRealOrderId().' Detail aanvraag: ')?>"><?php echo  $this->__('Bericht Zorgpunt') ?></a></span>
		    </td>
            <td class="a-center view">
                <span class="nobr"><a href="<?php echo $this->getViewOrderUrl($_order) ?>"><?php echo $this->__('Bekijk bestelling') ?></a></span>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('Your patients have placed no orders.'); ?></p>
<?php endif ?>
