<div class="page-title">
<h1><?php echo $this->__('Stock Overview') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>

<?php 
	  $_stock = $this->getStock();
	  
	  $currentpage = Mage::getBlockSingleton('page/html_pager')->getCurrentPage();
	  $perpage = Mage::getBlockSingleton('page/html_pager')->getLimit();
	  $_stock->getSelect()->limitPage($currentpage, $perpage);
?>
<?php echo $this->getChildHtml('info');?>
<?php if($_stock->getSize()): ?>
<table class="data-table orders" id="my-mstock-table">
    <col width="1" />
    <col/>
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th class="text"><?php echo $this->__('Product code') ?></th>
            <th class="text"><?php echo $this->__('Product') ?></th> 
            <th class="number"><span class="nobr"><?php echo $this->__('Quantity in stock') ?></span></th>
            <th class="number"><span class="nobr"><?php echo $this->__('Quantity in rent') ?></span></th>
            <th class="date"><span class="nobr"><?php echo $this->__('Last update') ?></span></th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; 
        foreach ($_stock as $_sitem): 
        	if(empty($_sitem)) continue;
        ?>
        <tr>
            <td class="text"><span class="nobr"><?php echo $this->__($_sitem['article_pcd']) ?></span></td>
            <td class="text"><span class="nobr"><?php echo $this->__($_sitem['article']) ?></span></td>
            <td class="number"><?php echo $_sitem['stock_quantity'] ?></td>
            <td class="number"><?php echo $_sitem['inrent_quantity'] ?></td>
            <td class="date"><span class="nobr"><?php echo $this->__($_sitem['update_dt']) ?></span></td>
        </tr><?php 
        endforeach; 
        ?>
    </tbody>
</table>
<?php else: ?>
    <p><?php echo $this->__('You have no stock for the moment.'); ?></p>
<?php endif ?>
<div class="buttons-set">
<p class=""><a href="<?php echo $this->escapeUrl($this->getRequesturl()) ?>"><?php echo $this->__('New Request') ?></a></p>
<p class=""><a href="<?php echo $this->escapeUrl($this->getRequestsurl()) ?>"><?php echo $this->__('Overview Requests') ?></a></p>

</div>
<script type="text/javascript">decorateTable('my-mstock-table');</script>
<?php /* echo $this->getMainPagerHtml();*/ ?>
