
<form id="co-hearedfrom-form" action="">
	<p> 
		<label id="bdoptiontext" class="elong"><?php echo $this->__('Birth Date Patient: ') ?><input class="tsmall" type="text" name="patientbdt" id="patientbdt" value=""/></label>
	 </p>
	<br/>
	<p> 
	<input id="vaph_order_id"  type="hidden" value="<?php echo $this->getVaphOrder() ?>"/>
	<?php if($this->getVaphOrder()){?>
		<label id="bdoptiontext" class="elong"><?php echo $this->__('VAPH documentnr.: ') ?><input class="input-text" type="text" name="vaph_doc_nr" id="vaph_doc_nr" value=""/></label>
		<div class="hidden">
	<?php }?> 
			<label id="deloptiontext" class=""><?php echo $this->__('Select a delivery option:') ?></label>
		<ul class="form-list"><ul id="dateoptions" class="control"></ul></ul>
	<?php if($this->getVaphOrder()){?></div><?php }?>
	 </p>
	<br/>
	
	<p>
	<label id="vlbl" for="getvoice"><?php echo $this->__('Who told you about us:'); ?></label><br/>
	<select id="getvoice" name="getvoice">
		<?php foreach($this->getHearedFromValues() as $_option): ?>
			<option value="<?php echo $_option ?>"
			<?php if((!empty($this->getSellerValue()) && $_option == $this->getSellerValue())
			|| ((empty($this->getSellerValue()) && $_option == $this->__('Select')))){
					echo 'selected';
			}?>
			><?php echo $_option ?></option>
		<?php endforeach; ?>
	</select>
	</p>
	<br/>
	<p><label for="myCustomerOrderComment"><?php echo $this->__('Add comment for Zorgpunt (optional):'); ?></label></p>
	<textarea name="myCustomerOrderComment" id="myCustomerOrderComment" style=”width:450px;height:100px;”></textarea>
	
	<div class="buttons-set" id="hearedfrom-buttons-container">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" title="<?php echo $this->__('Continue') ?>" onclick=""><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="hearedfrom-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
		</span>
    </div>

</form>


<script type="text/javascript">
//<![CDATA[

var Hearedfrom = Class.create();
Hearedfrom.prototype = {
    initialize: function(form, saveUrl){
        this.form = form;
        if ($(this.form)) {
            $(this.form).observe('submit', function(event){this.save();Event.stop(event);}.bind(this));
        }
        this.saveUrl = saveUrl;
        this.onSave = this.nextStep.bindAsEventListener(this);
        this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
    },

    save: function(){
        if (checkout.loadWaiting!=false) return;

        var validator = new Validation(this.form);
        if (validator.validate()) {

            checkout.setLoadWaiting('hearedfrom');


            var request = new Ajax.Request(
                this.saveUrl,
                {
                    method: 'post',
                    onComplete: this.onComplete,
                    onSuccess: this.onSave,
                    onFailure: checkout.ajaxFailure.bind(checkout),
                    parameters: Form.serialize(this.form)
                }
            );
        }
    },

    resetLoadWaiting: function(transport){
        checkout.setLoadWaiting(false);
    },

    nextStep: function(transport){
        if (transport && transport.responseText){
            try{
                response = eval('(' + transport.responseText + ')');
            }
            catch (e) {
                response = {};
            }
        }

        if (response.error){
            if ((typeof response.message) == 'string') {
                alert(response.message);
            } else {
                if (window.billingRegionUpdater) {
                    billingRegionUpdater.update();
                }

                alert(response.message.join("\n"));
            }

            return false;
        }

        checkout.setStepResponse(response);
    }    
}

var hearedfrom = new Hearedfrom('co-hearedfrom-form', '<?php echo $this->getUrl('checkout/onepage/saveHearedfrom') ?>');

//]]>
</script>
