
<form id="co-patient-form" action="">
	<div class="fieldset">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <ul class="form-list">
	<?php if ($this->customerHasAddresses()): ?>
        <li class="wide">
            <label for="patient-address-select"><?php echo $this->__('Select a patient or enter a new patient.') ?></label>
            <div class="input-box">
                <?php echo $this->getAddressesHtmlSelect('patient') ?>
            </div>
        </li>
        <?php endif; ?>
        <li id="patient-new-address-form" class="scaffold-form">
        	<div class="fieldset">
			<input type="hidden" name="patient[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="patient:address_id" />
	        <ul>
	    	<li class="wide">
	        	<label for="patient:firstname" class="required"><em>*</em><?php echo $this->__('Patient Firstname') ?></label>
	            <div class="input-box">
	            	<input type="text" title="<?php echo $this->__('Firstname') ?>" name="patient[firstname]" id="patient:firstname" value="<?php echo $this->escapeHtml($this->getPatientFirstname()) ?>" maxlength="255" class="input-text required-entry"/>
	            </div>
	        </li>
	        <li class="wide">
	        	<label for="patient:name" class="required"><em>*</em><?php echo $this->__('Patient Name') ?></label>
	            <div class="input-box">
	            	<input type="text" title="<?php echo $this->__('Name') ?>" name="patient[lastname]" id="patient:lastname" value="<?php echo $this->escapeHtml($this->getPatientName()) ?>" maxlength="255" class="input-text required-entry"/>
	            </div>
	        </li>
		   <li class="fields">
	        <?php if(!$this->isCustomerLoggedIn()): ?>
	           	<div class="field">
					<label for="patient:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
					<div class="input-box">
						<input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="patient[email]" id="patient:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
					</div>
				</div>
	        <?php endif; ?>
	        </li>
	        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
	        <li class="wide">
				<label for="patient:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
					<div class="input-box">
						<input type="text" title="<?php echo $this->__('Street Address') ?>" name="patient[street][]" id="patient:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
					</div>
	        </li>
	        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
	        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
	        <li class="wide">
				<label for="patient:street<?php echo $_i ?>"><?php echo $this->__('Street Address %s', $_i) ?></label>
					<div class="input-box">
						<input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="patient[street][]" id="patient:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
					</div>
	        </li>
	        <?php endfor; ?>        		
	        <li class="fields">
				<div class="field">
					<label for="patient:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
					<div class="input-box">
	 					<input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="patient[postcode]" id="patient:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
					</div>
				</div>
                <div class="field">
                    <label for="patient:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                    <div class="input-box">
                         <input type="text" title="<?php echo $this->__('City') ?>" name="patient[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="patient:city" />
                    </div>
                </div>
                <div class="field" style="display:none;">
                     <label for="patient:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                     <div class="input-box">
                         <select id="patient:region_id" name="patient[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                             <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                         </select>
                        <script type="text/javascript">
                            //<![CDATA[
                                $('patient:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                            //]]>
                        </script>
                        <input type="text" id="patient:region" name="patient[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                    </div>
                </div>
		</li>
		<li class="fields">
			<div class="field">
				<label for="patient:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
				<div class="input-box">
					<?php echo $this->getCountryHtmlSelect('patient') ?>
	 			</div>
			</div>
		</li>
		<li class="fields">
			<div class="field">
				<label for="patient:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
	 			<div class="input-box">
					<input type="tel" name="patient[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="patient:telephone" />
				</div>
			</div>
		</li>
		<?php if($this->isCustomerLoggedIn()): ?>
		<li class="fields">
			<div class="field">
				<label for="patient:email2"><?php echo $this->__('Contact email') ?></label>
				<div class="input-box">
					<input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="patient[email2]" id="patient:email2" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email" />
				</div>
			</div>
		</li>
		<?php endif; ?>
	        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
	        <li class="fields">
	        	<div class="field">
	           	<?php echo $_dob->setDate($this->getPatientBirthdate())->setFieldIdFormat('patient:%s')->setFieldNameFormat('patient[%s]')->toHtml() ?>
	        </div>
		</li>
		<li class="fields">
			 <?php 
	        $_gender = $this->getLayout()->createBlock('customer/widget_gender');
	        if ($_gender->isEnabled()): ?>
		          <div class="field">
		          <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('patient:%s')->setFieldNameFormat('patient[%s]')->toHtml() ?>
		         </div>
		    <?php endif ?>
		</li>
		 <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
		<li class="control">
	    	<input type="checkbox" name="patient[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="patient:save_in_address_book" onchange="if(window.billing) billing.setSameAsPatient(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
	    	<label for="patient:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
		</li>
		<?php else:?>
		<li class="no-display"><input type="hidden" name="patient[save_in_address_book]" value="1" /></li>
		<?php endif; ?>
		
         </ul>
       </div>
     </li>
    </ul>
    <ul class="form-list">
    <li class="control">
		<input type="checkbox" name="patient[use_for_billing]" value="1" title="<?php echo $this->__('Use for billing') ?>" id="patient:use_for_billing" onchange="patient.setUseForBilling();" checked="checked" class="checkbox" />
		<label for="patient:use_for_billing"><?php echo $this->__('Use for billing') ?></label>
     </li>
    </ul>
	<div class="buttons-set" id="patient-buttons-container">
        <button type="button" class="button" title="<?php echo $this->__('Continue') ?>" onclick="patient.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="patient-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
		</span>
    </div>

</form>


<script type="text/javascript">
//<![CDATA[

var patient = new Patient('co-patient-form', '<?php echo $this->getUrl('checkout/onepage/savePatient') ?>');
var patientForm = new VarienForm('co-patient-form');
//]]>
</script>
