<?php
/**
 * Magento
 *
 * SHE added link to Zorgpunt Apotheken
 *
 * @category    design
 * @package     brainworx_custom - edit rwd_default
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php $_menu = $this->getHtml('level-top') ?>

<?php if($_menu): ?>
    <nav id="nav">
        <ol class="nav-primary">
            <?php echo $_menu ?>  
             <li class="level0 "><a href="<?php echo $this->getUrl('incontinentie') ?>" class="level0">Incontinentie</a></li>
             <li class="level0 nav-4 parent"><a href="" class="level0 has-children">Diensten</a>
             	<ul class="level0">
                    
             		<li  class="level1 nav-4-1 first"><a class="level1" href="<?php echo $this->getUrl('thuisverpleging') ?>" class="level1 ">Thuisverpleging</a></li>
             		<li  class="level1 nav-4-2 "><a class="level1" href="<?php echo $this->getUrl('zuster-in-huis') ?>" class="level1 ">Zorgassistent</a></li>
             		<li  class="level1 nav-4-3 last"><a class="level1" href="<?php echo $this->getUrl('vaph') ?>" class="level1 ">VAPH</a></li>
                 </ul>
             </li>         
        	 <li class="level0 "><a href="<?php echo $this->getUrl('zorgpunt-apotheken') ?>" class="level0">Zorgpunt Apotheken</a></li>
             <li class="level0 nav-5 parent"><a href="<?php echo $this->getUrl('over') ?>" class="level0 has-children">Over ons</a>
             <ul class="level0">
             		<li  class="level1 nav-5-1 first"><a class="level1" href="<?php echo $this->getUrl('over') ?>" class="level1 ">Over ons</a></li>
             	    <li  class="level1 nav-5-2 "><a class="level1" href="<?php echo $this->getUrl('onze-troeven') ?>" class="level1 ">Onze troeven</a></li>
             		<li  class="level1 nav-5-3 last"><a class="level1" href="<?php echo $this->getUrl('bestellen-tot-betalen') ?>" class="level1 ">Van bestellen tot betalen</a></li>
             </ul>
             </li>
        	 <li class="level0 last"><a href="<?php echo $this->getUrl('contact') ?>" class="level0">Contact</a></li>
        </ol>
    </nav>
<?php endif ?>
