<?php
/**
 * Magento
 *
 * SHE added link to Zorgpunt Apotheken
 *
 * @category    design
 * @package     brainworx_custom - edit rwd_default
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php $_menu = $this->getHtml('level-top') ?>

<?php if($_menu): ?>
    <nav id="nav">
        <ol class="nav-primary">
            <?php echo $_menu ?>   
             <li class="level0 parent"><a href="" class="level0">Diensten</a>
             	<ul class="level0">
             		<li class="level1 view-all"><a class="level1" href="http://localhost/magento/verhuur.html">Alle Verhuur</a></li>
             		<li  class="level1 nav-1-1 first"><a class="level1" href="<?php echo $this->getUrl('vaph') ?>" class="level1 ">VAPH</a></li>
             		<li  class="level1 nav-1-2 last"><a class="level1" href="<?php echo $this->getUrl('zorg-au-pairs') ?>" class="level1 ">Zorg au-pairs</a></li>
             		<li  class="level1 nav-1-1 first"><a class="level1" href="<?php echo $this->getUrl('nursing') ?>" class="level1 ">Verpleging</a></li>
     
             	</ul>
             </li>         
        	 <li class="level0 parent"><a href="<?php echo $this->getUrl('documenten') ?>" class="level0">Documenten</a></li>
             <li class="level0 parent"><a href="<?php echo $this->getUrl('about') ?>" class="level0">Over ons</a></li>
        	 <li class="level0 parent"><a href="<?php echo $this->getUrl('contact') ?>" class="level0">Contact</a></li>
        </ol>
    </nav>
<?php endif ?>
