<?php
/**
 * Magento
 * Brainworx template for delivery information
 * 
 */
?>
<?php 
$_order = $this->getOrder();
$_shipment = $this->getShipment();?>
<div class="box-left">
    <!--Account Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('depot')->__('Customerinformation') ?></h4>
            <div class="tools"><?php echo $this->getAccountEditLink()?></div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('depot')->__('Name') ?></label></td>
                    <td class="value">
                    <?php if ($_customerUrl=$this->getCustomerViewUrl()) : ?>
                        <a href="<?php echo $_customerUrl ?>" target="_blank"><strong><?php echo $this->escapeHtml($_order->getCustomerName()) ?></strong></a>
                    <?php else: ?>
                        <strong><?php echo $this->escapeHtml($_order->getCustomerName()) ?></strong>
                    <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Email') ?></label></td>
                    <td class="value"><a href="mailto:<?php echo $_order->getCustomerEmail() ?>"><strong><?php echo $_order->getCustomerEmail() ?></strong></a></td>
                </tr>
                 <tr>
                    <td class="label"><label><?php echo Mage::helper('depot')->__('Phone') ?></label></td>
                    <td class="value"><strong><?php echo $_order->getBillingAddress()->getTelephone() ?></strong></td>
                </tr>
                  <tr>
                    <td class="label"><label><?php echo Mage::helper('depot')->__('Deliveryaddress') ?></label></td>
                    <td class="value"><strong><?php echo $_order->getShippingAddress()->getData()['street'].
									', '.$_order->getShippingAddress()->getData()['postcode'].
                    				' '. $_order->getShippingAddress()->getData()['city'] ?></strong></td>
                </tr>
               
                </table>
            </div>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Account Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('depot')->__('Orderinformation') ?></h4>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                 <table cellspacing="0" class="data order-tables">
        <col />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th><?php echo $this->helper('sales')->__('Product') ?></th>
                <th class="a-center last"><span class="nobr"><?php echo $this->helper('sales')->__('Qty Shipped') ?></span></th>
            </tr>
        </thead>
        <?php $_items = $_shipment->getAllItems() ?>
        <?php $_i=0;foreach ($_items as $_item): if ($_item->getOrderItem()->getIsVirtual() || $_item->getOrderItem()->getParentItem()): continue; endif; $_i++ ?>
            <tbody class="<?php echo $_i%2?'odd':'even' ?>">
				<tr class="border">
				    <td><?php echo $this->getColumnHtml($_item, 'name') ?></td>
				    <td class="a-center last"><?php echo $_item->getQty()*1/*$this->getColumnHtml($_item, 'qty') */ ?></td>
				</tr>
            </tbody>
        <?php endforeach; ?>
    </table>
            </div>
        </div>
    </div>
</div>

<div class="clear"></div>