<?php
/**
 * Brainworx override in order to enable stockrefill
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2014 X.commerce, Inc. (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /** @var $this Mage_Checkout_Block_Onepage_Shipping_Method_Available */ ?>
<?php $_shippingRateGroups = $this->getShippingRates(); 
$pickup = Mage::getSingleton('core/session')->getPickupPossible();
$delivery = Mage::getSingleton('core/session')->getDeliveryPossible();
if(!$pickup && !$delivery){$delivery=true;}
?>
<?php ?>
<?php if (!$_shippingRateGroups): ?>
    <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else: ?>
    <dl class="sp-methods">
    <?php $shippingCodePrice = array(); ?>
    <?php $_sole = count($_shippingRateGroups) == 1; 
    foreach ($_shippingRateGroups as $code => $_rates): ?>
        <dt><?php if($code == "freeshipping" && !$pickup ){continue;} 
        	else if($code == "tablerate" &&!$delivery ){continue;}
        	else if($code == "normalrate2" &&!$delivery ){continue;}
            else if($code == "salesrate" &&!$delivery ){continue;}
        	else echo $this->escapeHtml($this->getCarrierName($code)); ?></dt>
        <dd>
            <ul>
            <?php 
            if($code == "tablerate" || $code=="salesrate" || $code=="specialrate"|| $code=="normalrate2"){
            	$showcheckboxfor = $code;
            }else{
            	$showcheckboxfor = null;
            	$hidecheckboxfor = $code;
            }
            $_sole = $_sole && count($_rates) == 1; 
            foreach ($_rates as $_rate): ?>
                <?php $shippingCodePrice[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
                <li>
                   <?php if ($_rate->getErrorMessage()): ?>
                    <ul class="messages"><li class="error-msg"><ul><li><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li></ul></li></ul>
                   <?php else: ?>
                        <?php if ($_sole) : ?>
                        <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
                        <?php else: ?>
                        <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()||$_rate->getCode()==='supplierrate_flatrate') echo ' checked="checked"' ?> class="radio"/>

                        <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                        <script type="text/javascript">
                            //<![CDATA[
                                lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                            //]]>
                        </script>
                        <?php endif; ?>

                        <?php endif; ?>
                        <label id="lb_<?php echo $_rate->getCode() ?>" for="s_method_<?php echo $_rate->getCode() ?>">
                        <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                        <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                        <?php echo $_excl; ?>
                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                        <?php endif; ?>
                        <?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                        <?php if ($_rate->getCode() === "tablerate_bestway" || $_rate->getCode() === "tablerate_weekend"|| $_rate->getCode() === "normalrate2_flatrate"): ?>
                       		<?php echo '<br>'.$this->__('Select a delivery date:') ?>
                       		<input class="tsmall labeldt" type="text" name="<?php echo $_rate->getCode() ?>_delrange" id="<?php echo $_rate->getCode() ?>_deldate" value="" />  
                         <?php elseif ($_rate->getCode() === "salesrate_flatrate" || $_rate->getCode() === "specialrate_urgent"|| $_rate->getCode() === "specialrate_urgent1"
                            || $_rate->getCode() === "specialrate_weekend"|| $_rate->getCode() === "specialrate_standard"|| $_rate->getCode() === "specialrate_flatrate"|| $_rate->getCode() === "specialrate_free"): ?>
                       		<?php echo $this->__('Select a delivery date:') ?>
                       		<input class="tsmall labeldt" type="text" name="<?php echo $_rate->getCode() ?>_delrange" id="<?php echo $_rate->getCode() ?>_deldate" value="" />  
                         <?php elseif ($_rate->getCode() === "tablerate_express"): ?>
                       		<?php echo '<br>'.$this->__('Delivery date:') ?>
                       		<input class="tsmall labeldt" type="text" name="<?php echo $_rate->getCode() ?>_delrange" id="<?php echo $_rate->getCode() ?>_deldate" value="" /> 
                        <?php elseif ($_rate->getCode() === "freeshipping_freeshipping" && !$this->getVaphOrder()): ?>
                       		<?php echo $this->__('Delivery date:') ?>
                       		<input class="tsmall labeldt" type="text" name="<?php echo $_rate->getCode() ?>_delrange" id="<?php echo $_rate->getCode() ?>_deldate" value="" /> 
                        
                        <?php endif; ?>                       
                        </label>
                   <?php endif ?>
                </li>
            <?php endforeach; ?>
            </ul>
        </dd>
        
        <?php if(!empty($showcheckboxfor)): ?>
     	<div id="onepage-checkout-shipping-method-address">
     		<ul class="form-list">
     			<li class="control">
     				<input type="checkbox" name=<?php echo $showcheckboxfor.'_use_for_shipping';?> id="patient:use_for_shipping" value="1" checked="checked" title="<?php echo  $this->__('Ship to billing address') ?>" class="checkbox" /><label for="use_for_shipping"><?php echo  $this->__('Ship to billing address') ?></label>
     			</li>
     		</ul>
     	</div>
        <?php else: ?>
        <input type="hidden" name=<?php echo $hidecheckboxfor.'_use_for_shipping';?> id="patient:use_for_shipping" value="1" />
        <?php endif;?>
    <?php endforeach; ?>
    
     	<input type="hidden" name='shipping[same_as_billing]' id="shipping:same_as_billing" value="1" />
    </dl>
    <p><label for="myCustomerOrderComment"><?php echo $this->__('Add comment for Zorgpunt (optional):'); ?></label></p>
	<textarea name="myCustomerOrderComment" id="myCustomerOrderComment" style="width:450px;height:100px;"></textarea>
	
	
</div>

<?php endif; ?>
