<div class="blok">
<div class="subcat-listing">
	<div class="homebar"><p class="verhuur">Verhuur</p></div>
	<div class="floated_img first">
		<a href="<?php echo Mage::getBaseUrl().'verhuur/bedden-en-toebehoren-te-huur.html'  ?>" title="bedden-en-toebehoren-te-huur">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verhuur_bedden.jpg')  ?>" alt="Verhuur Bedden en toebehoren" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verhuur/mobiliteit-te-huur.html'  ?>" title="mobiliteit-te-huur">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verhuur_mobiliteit.jpg')  ?>" alt="Verhuur Mobiliteit" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verhuur/revalidatie-te-huur.html'  ?>" title="revalidatie-te-huur">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verhuur_revalidatie.jpg')  ?>" alt="Verhuur Revalidatie" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verhuur/toilet-verzorging-te-huur.html'  ?>" title="toilet-verzorging-te-huur">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verhuur_toilet.jpg')  ?>" alt="Verhuur Toiletverzorging" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verhuur/zetels-en-comfort-te-huur.html'  ?>" title="zetels-en-comfort-te-huur">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verhuur_zetels.jpg')  ?>" alt="Verhuur Zetels en comfort" />
		</a>
	</div>
</div>
<div class="subcat-listing">
	<div class="homebar verkoop"><p  class="verkoop">Verkoop</p></div>

	<div class="floated_img first">
		<a href="<?php echo Mage::getBaseUrl().'verkoop/bedden-en-toebehoren.html'  ?>" title="bedden-en-toebehoren">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verkoop_bedden.jpg')  ?>" alt="Verkoop Bedden en toebehoren" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verkoop/mobiliteit.html'  ?>" title="mobiliteit">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verkoop_mobiliteit.jpg')  ?>" alt="Verkoop Mobiliteit" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verkoop/volledig-terugbetaalde-mobiliteit.html'  ?>" title="volledig-terugbetaalde-mobiliteit">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verkoop_terugbetaalde_mobiliteit.jpg')  ?>" alt="Verkoop terugbetaalde Mbiliteit" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verkoop/zetels-en-comfort.html'  ?>" title="zetels-en-comfort">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verkoop_zetels.jpg')  ?>" alt="Verkoop Zetels en comfort" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'incontinentie/'  ?>" title="incontinentie">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verkoop_incontinentie.jpg')  ?>" alt="Verkoop Incontinentie" />
		</a>
	</div>
</div>
</div>
