<!-- SHE page to display a grid overview for all second level categories -->
<?php //$this->getSkinUrl(‘images/sampleimage.jpg’) 
//Mage::getBaseUrl() ?>
<div class="blok">
<div class="subcat-listing">
	<div class="homebar"><p class="verhuur">Verhuur</p></div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verhuur/bedden-en-toebehoren-te-huur.html'  ?>" title="bedden-en-toebehoren-te-huur">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verhuur_bedden.png')  ?>" alt="Verhuur Bedden en toebehoren" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verhuur/mobiliteit-te-huur.html'  ?>" title="mobiliteit-te-huur">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verhuur_mobiliteit.png')  ?>" alt="Verhuur Mobiliteit" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verhuur/revalidatie-te-huur.html'  ?>" title="revalidatie-te-huur">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verhuur_revalidatie.png')  ?>" alt="Verhuur Revalidatie" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verhuur/toilet-verzorging-te-huur.html'  ?>" title="toilet-verzorging-te-huur">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verhuur_toilet.png')  ?>" alt="Verhuur Toiletverzorging" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verhuur/zetels-en-comfort-te-huur.html'  ?>" title="zetels-en-comfort-te-huur">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verhuur_bedden.png')  ?>" alt="Verhuur Zetels en comfort" />
		</a>
	</div>
</div>
<div class="subcat-listing">
	<div class="homebar verkoop"><p  class="verkoop">Verkoop</p></div>

	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verkoop/bedden-en-toebehoren.html'  ?>" title="bedden-en-toebehoren">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verkoop_bedden.png')  ?>" alt="Verkoop Bedden en toebehoren" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verkoop/incontinentie.html'  ?>" title="incontinentie">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verkoop_incontinentie.png')  ?>" alt="Verkoop Incontinentie" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verkoop/revalidatie.html'  ?>" title="revalidatie">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verkoop_revalidatie.png')  ?>" alt="Verkoop Revalidatie" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verkoop/toilet-verzorging.html'  ?>" title="toilet-verzorging">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verkoop_toilet.png')  ?>" alt="Verkoop Toiletverzorging" />
		</a>
	</div>
	<div class="floated_img">
		<a href="<?php echo Mage::getBaseUrl().'verkoop/zetels-en-comfort.html'  ?>" title="zetels-en-comfort">
		<img class="cat_img" src="<?php echo $this->getSkinUrl('images/verkoop_bedden.png')  ?>" alt="Verkoop Zetels en comfort" />
		</a>
	</div>
</div>
</div>
