<?php
/**
 * Magento
 * removed linkes
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2014 X.commerce, Inc. (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if ($this->getCheckout()->getStepData('billing', 'complete')): ?>
<dt class="complete">
    <?php echo $this->__('Billing Information') ?>
</dt>
<dd class="complete">
    <address><?php echo $this->getBilling()->format('html') ?></address>
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Billing Information') ?>
</dt>
<?php endif; ?>
