<?php

?>
<?php if ($this->getCheckout()->getStepData('patient', 'complete')): ?>
<dt class="complete">
    <?php echo $this->__('Patient information') ?>
</dt>
<dd class="complete">
    <address><?php echo $this->getPatient()->format('html') ?></address>
    <?php echo  $this->__('Birth Date Patient') .': '.$this->getPatientBirthDate();?>
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Patient information') ?>
</dt>
<?php endif; ?>
