<?php
/**
 * Magento
 *
 * removed link
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2014 X.commerce, Inc. (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
<dt class="complete">
    <?php echo $this->__('Payment Method') ?>
</dt>
<dd class="complete">
    <?php echo $this->getPaymentHtml() ?>
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Payment Method') ?>
</dt>
<?php endif; ?>

