<?php
/**
 * SHE: update link to copy of order
 */
?>
<div class="page-title">
    <h2><?php echo $this->__('Your order has been received.') ?></h2>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>


<?php if ($this->getOrderId()):?>
<?php if ($this->getCanViewOrder()) :?>
 <p><?php echo $this->__('Your order has been received. You will receive an order confirmation email with for your order with number %s.',sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
<?php  else :?>
   <p><?php echo $this->__('Your order has been received. You will receive an order confirmation email with for your order with number %s.',$this->escapeHtml($this->getOrderId())); ?></p>
<?php endif;?>
   
<?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
    <p>
        <?php echo $this->__('Klik <a href="%s" onclick="this.target=\'_blank\'">hier</a> om een kopie van je bestelling te printen.', $this->getPrintUrl()) ?>
        <?php echo $this->__('In case you have chosen for home delivery, you will be contacted by us.')?>
        <?php echo $this->__('We thank you for placing this order.')?>
        <?php echo $this->getChildHtml() ?>
    </p>
<?php endif;?>
<?php endif;?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
<?php endif;?>

<?php if ($profiles = $this->getRecurringProfiles()):?>
<p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
<ul class="disc">
<?php foreach($profiles as $profile):?>
<?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
    <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
<?php endforeach;?>
</ul>
<?php endif;?>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('To our homepage') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('To our homepage') ?></span></span></button>
</div>
