<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * SHE add to button has different text and action depending condition user
 */
?>

<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php $_product = $this->getProduct(); 
/*Brainworx*/
	$_addOK = false;
	$_catSI = false;
	if(Mage::getSingleton('customer/session')->isLoggedIn()){
		$groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
		if(Mage::getModel('core/variable')->setStoreId(Mage::app()->getStore()->getId())->loadByCode('ZORGP_GID')->getValue('text') == $groupId) {
			$_addOK = true;
		}
	}
	$_catsviaapp = explode(",",Mage::getModel('core/variable')->setStoreId(Mage::app()->getStore()->getId())->loadByCode('CATS_VIAAPP_INV')->getValue('text'));
	foreach($_product->getCategoryIds()as $cat){
		if(in_array($cat,$_catsviaapp)){
			$_catSI = true;
			break;
		}
	}
	if($_catSI && !$_addOK){
		$buttonTitle = $this->__('Exclusive for farmacie');
		?>
		<div class="add-to-cart">
		        <div class="add-to-cart-buttons">
		            <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="location.href='<?php echo $this->__('farmacielink');?>'"><span><span><?php echo $buttonTitle ?></span></span></button>
		            <?php echo $this->getChildHtml('', true, true) ?>
		        </div>
		    </div>
		<?php 
		return;
	}
?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <div class="qty-wrapper">
            <label for="qty"><?php echo $this->__('Qty:') ?></label>
            <input type="text" pattern="\d*" name="qty" id="qty" maxlength="12" value="<?php echo max($this->getProductDefaultQty() * 1, 1) ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        </div>
        <?php endif; ?>
        <div class="add-to-cart-buttons">
            <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
            <?php echo $this->getChildHtml('', true, true) ?>
        </div>
    </div>
<?php endif; ?>
