<?php $_order = $this->getOrder() ?>

<?php
$orderAdminDate = $this->formatDate($_order->getCreatedAtDate(), 'medium', true);
$orderStoreDate = $this->formatDate($_order->getCreatedAtStoreDate(), 'medium', true);
$_comment = $_order->getCommentToZorgpunt();
if(empty($_comment)){ $_comment= Mage::helper('sales')->__('No comment provided');}		
$_birthdate = null;
if(!empty($_order->getPatientBirthDate())){
	$_birthdate = $_order->getPatientBirthDate();
}
?>
<div class="box-left">
    <!--Order Information-->
    <div class="entry-edit">
        <?php if ($_order->getEmailSent()):
            $_email=$this->__('Order confirmation email sent');
        else:
            $_email=$this->__('Order confirmation email not sent');
        endif; ?>
        <div class="entry-edit-head">
        <?php if ($this->getNoUseOrderLink()): ?>
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?> (<?php echo $_email ?>)</h4>
        <?php else: ?>
            <a href="<?php echo $this->getViewUrl($_order->getId()) ?>"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?></a>
            <strong>(<?php echo $_email ?>)</strong>
        <?php endif; ?>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date') ?></label></td>
                <td><strong><?php echo $orderAdminDate ?></strong></td>
            </tr>
            <?php if ($orderAdminDate != $orderStoreDate):?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date (%s)', $_order->getCreatedAtStoreDate()->getTimezone()) ?></label></td>
                <td><strong><?php echo $orderStoreDate ?></strong></td>
            </tr>
            <?php endif;?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Status') ?></label></td>
                <td><strong><span id="order_status"><?php echo $_order->getStatusLabel() ?></span></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Purchased From') ?></label></td>
                <td><strong><?php echo $this->getOrderStoreName() ?></strong></td>
            </tr>
            <?php if($_order->getRelationChildId()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Link to the new order') ?></label></td>
                <td><a href="<?php echo $this->getViewUrl($_order->getRelationChildId()) ?>">
                    <?php echo $_order->getRelationChildRealId() ?>
                </a></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getRelationParentId()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Link to the previous order') ?></label></td>
                <td><a href="<?php echo $this->getViewUrl($_order->getRelationParentId()) ?>">
                    <?php echo $_order->getRelationParentRealId() ?>
                </a></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getRemoteIp()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Placed from IP') ?></label></td>
                <td><strong><?php echo $_order->getRemoteIp() ?></strong></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getGlobalCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                <td><strong><?php echo $_order->getBaseToGlobalRate() ?></strong></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getOrderCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                <td><strong><?php echo $_order->getBaseToOrderRate() ?></strong></td>
            </tr>
            <?php endif; ?>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Account Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Account Information') ?></h4>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Name') ?></label></td>
                    <td>
                    <?php if ($_customerUrl=$this->getCustomerViewUrl()) : ?>
                        <a href="<?php echo $_customerUrl ?>" target="_blank"><strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong></a>
                    <?php else: ?>
                        <strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong>
                    <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Email') ?></label></td>
                    <td><a href="mailto:<?php echo $_order->getCustomerEmail() ?>"><strong><?php echo $_order->getCustomerEmail() ?></strong></a></td>
                </tr>
                <?php if ($_groupName=$this->getCustomerGroupName()) : ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Group') ?></label></td>
                    <td><strong><?php echo $_groupName ?></strong></td>
                </tr>
                <?php endif; ?>
                <?php if ($_dob=$this->getOrder()->getCustomerDob()) : ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Date of Birth') ?></label></td>
                    <td><strong><?php echo Mage::helper('core')->formatDate($_dob, 'medium') ?></strong></td>
                </tr>
                <?php endif; ?>
                <?php if ($_taxvat = $_order->getCustomerTaxvat()):?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('TAX/VAT Number') ?></label></label></td>
                    <td><strong><?php echo $this->htmlEscape($_taxvat)?></strong></td>
                </tr>
                <?php endif;?>
                </table>
            </div>
        </div>
    </div>
</div>


<div class="box-right">
    <!--Brainworx Module Placeholder - Where did you hear about us -->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-hearedfrom"><?php echo Mage::helper('checkout')->__('Additional info') ?></h4>
        	<div class="tooltip"><a href="#" onclick="loadHearedfromEdit()"><?php echo $this->__('MageWorx_OrdersEdit::Change') ?></a></div>
        </div>
         <fieldset>
         	<div id='seller_block' class=''>
	         <p>
	          	 <div id="sellerblock">
	          	 <label class="normal" ><?php echo Mage::helper('sales')->__('Zorgpunter:') ?></label>
		       	  <strong>
					<?php
					//TODO add to custom Mage_Adminhtml_Block_Sales_Order_View_Info
					$seller = Mage::getModel("hearedfrom/salesSeller")->loadByOrderId($_order->getIncrementId());
					$user =  Mage::getModel("hearedfrom/salesForce")->load($seller['user_id'])->getData("user_nm");
					echo Mage::getModel("hearedfrom/salesForce")->load($seller['user_id'])->getData("user_nm");?>
				  </strong>					  	
				  </div>
				  <!-- Brainworx: make seller editable -->
				  <div id="sellerblockedit" class="hidden">
				  <label class="normal" ><?php echo Mage::helper('sales')->__('Zorgpunter:') ?></label>
		       	 
					  <input type="hidden" id="ooid" value="<?php echo$_order->getIncrementId()?>"/>
					  <select id="sellerusernm" name="sellerusernm">
						<?php foreach(Mage::getModel("hearedfrom/salesForce")->getUserNames() as $_option): ?>
							<option value="<?php echo $_option ?>"
							<?php 
							if(!empty($user) && $_option == $user){
									echo 'selected';
							}?>
							><?php echo $_option ?></option>
						<?php endforeach; ?>
					  </select>
					  <br><br>
					  <span class="left">
					  <button class="f-right" type="button" title="<?php echo $this->__('MageWorx_OrdersEdit::Change') ?>" 
					   onclick="loadHearedfromDefault()" >
					        <span><span><?php echo $this->__('MageWorx_OrdersEdit::Cancel') ?></span></span>
					   </button>
					   </span>
					   <span class="right">
					   <button type="submit" class="f-right" type="button" title="<?php echo $this->__('MageWorx_OrdersEdit::Change') ?>" 
					   onclick="updateHearedfrom('<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/hearedfrom/update');?>')" >
					        <span><span><?php echo $this->__('MageWorx_OrdersEdit::Submit') ?></span></span>
					    </button>
					    </span>
					    <br><br>
				  </div>
			  </p>	
		  	</div>
			<div id="customer_comments_block">
				<p>
			    	<span class="field-row">
			        <label class="normal" for="myCustomerOrderComment"><?php echo Mage::helper('sales')->__('Comment for Zorgpunt:') ?></label>
			        <textarea id="myCustomerOrderComment" name="myCustomerOrderComment" style="height:6em; width:99%;" disabled><?php echo $_comment;?></textarea>
			    	</span>
		    	</p>
	    	</div>
	    	<div id="birthdate_block">
	    		<div id="birthdateblock" class="">
	    		<p>
	    			<span class="field-row">
			        <label class="normal" for="patientBirthDate"><?php echo Mage::helper('checkout')->__('Birth Date Patient: ') ?></label>
			        <?php if($_birthdate != null){echo $this->formatDate($_birthdate, 'medium');}
			        else{echo Mage::helper('checkout')->__('Not provided'); }?>
			    	</span>
	    		</p>
	    		</div>
	    		<!-- Brainworx: make seller editable -->
				  <div id="birthdateblockedit" class="hidden">
				  	<span class="field-row">
				  	  <input type="hidden" id="ooid" value="<?php echo$_order->getIncrementId()?>"/>
					  <label class="normal" for="patientBirthDate"><?php echo Mage::helper('checkout')->__('Birth Date Patient: ') ?></label>
			          <input id="patientBirthDate" name="patientBirthDate" value='<?php echo date("d-m-Y", strtotime($_birthdate));?>'></input>
					  <br><br>
					  <span class="left">
					  <button class="f-right" type="button" title="<?php echo $this->__('MageWorx_OrdersEdit::Change') ?>" 
					   onclick="loadHearedfromDefault()" >
					        <span><span><?php echo $this->__('MageWorx_OrdersEdit::Cancel') ?></span></span>
					   </button>
					   </span>
					   <span class="right">
					   <button type="submit" class="f-right" type="button" title="<?php echo $this->__('MageWorx_OrdersEdit::Change') ?>" 
					   onclick="updateBirthdate('<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/hearedfrom/updateBirthDate');?>')" >
					        <span><span><?php echo $this->__('MageWorx_OrdersEdit::Submit') ?></span></span>
					    </button>
					    </span>
					    <br><br>
				  </div>
	    	</div>
	    	<div id="vaph_block">
	    		<div id="vaphblock" class="">
	    		<p>
	    			<span class="field-row">
			        <label class="normal" for="vaphdocnr"><?php echo Mage::helper('hearedfrom')->__('VAPH Documentnr.: ') ?></label>
			        <?php if($_order->getVaphDocNr() != null){echo $_order->getVaphDocNr();}
			        else{echo Mage::helper('checkout')->__('Not provided'); }?>
			    	</span>
	    		</p>
	    		</div>
	    		<!-- Brainworx: make vaph editable -->
				  <div id="vaphblockedit" class="hidden">
				  	<span class="field-row">
				  	  <input type="hidden" id="ooid" value="<?php echo$_order->getIncrementId()?>"/>
					  <label class="normal" for="vaphdocnr"><?php echo Mage::helper('checkout')->__('VAPH Documentnr.: ') ?></label>
			          <input id="vaphdocnr" name="vaphdocnr" value='<?php echo $_order->getVaphDocNr()?>'></input>
					  <br><br>
					  <span class="left">
					  <button class="f-right" type="button" title="<?php echo $this->__('MageWorx_OrdersEdit::Change') ?>" 
					   onclick="loadHearedfromDefault()" >
					        <span><span><?php echo $this->__('MageWorx_OrdersEdit::Cancel') ?></span></span>
					   </button>
					   </span>
					   <span class="right">
					   <button type="submit" class="f-right" type="button" title="<?php echo $this->__('MageWorx_OrdersEdit::Change') ?>" 
					   onclick="updateVaphDocnr('<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/hearedfrom/updateVaphDocnr');?>')" >
					        <span><span><?php echo $this->__('MageWorx_OrdersEdit::Submit') ?></span></span>
					    </button>
					    </span>
					    <br><br>
				  </div>
	    	</div>
		</fieldset>
    </div>
</div>

<div class="clear"></div>

<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-billing-address"><?php echo Mage::helper('sales')->__('Billing Address') ?></h4>
        </div>
        <fieldset>
            <address><?php echo $_order->getBillingAddress()->getFormated(true) ?></address>
        </fieldset>
    </div>
</div>

<?php if (!$this->getOrder()->getIsVirtual()): ?>
<div class="box-right">
    <!--Shipping Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('sales')->__('Shipping Address') ?></h4>
        </div>
        <fieldset>
            <address><?php echo $_order->getShippingAddress()->getFormated(true) ?></address>
        </fieldset>
    </div>
</div>
<div class="clear"></div>
<?php endif; ?>