<?php
/**
 * Magento
 *
 * Added default tracking number
 */
?>
<?php /** @var $this Mage_Adminhtml_Block_Sales_Order_Shipment_View_Tracking */ 
$count = 1;
?>
<div class="field-row grid" id="shipment_tracking_info">
<table cellspacing="0" class="data">
    <col width="100" />
    <col />
    <col />
    <col width="80" />
    <thead>
        <tr class="headings">
            <th><?php echo Mage::helper('sales')->__('Carrier') ?></th>
            
            <th><?php echo Mage::helper('sales')->__('Title') ?></th>
           
            <th><?php echo Mage::helper('sales')->__('TrackingNumber') ?></th>
            
            <th class="last"><?php echo Mage::helper('sales')->__('Action') ?></th>
        </tr>
    </thead>
    
<?php if($_tracks = $this->getShipment()->getAllTracks()): ?>
    <tbody>
    <?php $i=0;foreach ($_tracks as $_track):$i++ ?>
        <tr class="<?php echo ($i%2==0)?'even':'odd' ?>">
            <td><?php echo $this->escapeHtml($this->getCarrierTitle($_track->getCarrierCode())) ?></td>
            
            <td><!-- Bw add link to delivery item -->
            <a href="<?php echo $this->getDeliveryUrl($_track) ?>"><?php echo $this->escapeHtml($_track->getTitle()) ?></a>
            <?php  ?></td>
         
             <td>
             	<a href="<?php echo $this->getDeliveryUrl($_track) ?>">
                <?php if ($_track->isCustom()): ?>
                <?php echo $this->escapeHtml($_track->getNumber()) ?>
                <?php else: ?>
                <?php echo $this->escapeHtml($_track->getNumber()) ?>
                <div id="shipment_tracking_info_response_<?php echo $_track->getId() ?>"></div>
                <?php endif; ?>
                </a>
            </td>
            <td class="last"><a href="#" onclick="deleteTrackingNumber('<?php echo $this->getRemoveUrl($_track) ?>'); return false;"><?php echo Mage::helper('sales')->__('Delete') ?></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <?php else :?>
    <!-- SHE moved this to the else block to have 1 depot per shipment -->
    <tfoot>
        <tr>
            <td>
                <select name="carrier" class="select" style="width:210px" onchange="selectCarrier(this)">
                    <option value=""><?php echo Mage::helper('sales')->__('Select')?></option>
                    <?php foreach ($this->getCarriers() as $_code=>$_name): ?>
                    <option value="<?php echo $_code ?>"><?php echo $this->escapeHtml($_name) ?></option>
                    <?php endforeach; ?>
                </select>
            </td>
           
            <td><input class="input-text" type="text" id="tracking_title" name="title" value="" /></td>
               
            <td><input class="input-text" type="text" id="tracking_number" name="number" value="" /></td>
            
            <td class="last"><?php echo $this->getSaveButtonHtml() ?></td>
        </tr>
    </tfoot>
<?php endif; ?>
</table>
</div>
<script type="text/javascript">
//<![CDATA[
var teller = 1;
function selectCarrier(elem) {
    var option = elem.options[elem.selectedIndex];
    $('tracking_title').value = option.value && option.value != 'custom' ? option.text : '';
    $('tracking_number').value = new Date().getTime()+(teller++);
}

function deleteTrackingNumber(url) {
    if (confirm('<?php echo Mage::helper('sales')->__('Are you sure?') ?>')) {
        submitAndReloadArea($('shipment_tracking_info').parentNode, url)
    }
}
//]]>
</script>
